# Week 2

## Question 1

In [7]:
M=[[11,12,13,14],[21,22,23,24],[31,32,33,34]]
M[0][-4]

11

In [2]:
for x in M:
    a=x[0]
    x[0]=x[1]
    x[1]=a

print(M)

[[12, 11, 13, 14], [22, 21, 23, 24], [32, 31, 33, 34]]


In [2]:
# Other solution 1

for i in range(len(M)):
    M[i][0], M[i][1] = M[i][1], M[i][0]
print(M)

[[12, 11, 13, 14], [22, 21, 23, 24], [32, 31, 33, 34]]


In [4]:
# Other solution 2

import numpy as np
arr=np.array(M)
arr[:,[0,1]] = arr[:,[1,0]]
print(arr)

[[12 11 13 14]
 [22 21 23 24]
 [32 31 33 34]]


## Question 2

In [10]:
M=[[0,3,2,4], [2,7,5,9], [6,1,2,3]]

In [4]:
maximal=M[0][0]
for x in range(len(M)):
    for y in range(len(M[x])):
        if M[x][y] > maximal:
            maximal=M[x][y]
            a=x
            b=y
print((a, b))
print(maximal)

(1, 3)
9


In [16]:
# Other solution 1

arr=np.array(M)
result=np.where(arr==np.amax(arr))
coordinates=tuple(zip(result[0], result[1]))

for coord in coordinates:
    print(coord)

(1, 3)


## Question 3

In [5]:
list_1 = [5, 3, 3, 10, 40]
list_2 = [40, 3, 40, 1, 2]
unique=[]

for i in range(len(list_1)):
    a=list_1[i]
    b=list_2[i]
    if a not in unique:
        unique.append(a)
    if b not in unique:
        unique.append(b)
        
print(len(unique))

6


## Question 4 

In [9]:
students = {"Jane":{"grade":90,"student_number":4012}, 
          "Pat":{"grade":81,"student_number":4052},
          "Denis":{"grade":70,"student_number":4089},
          "Max":{"grade":72,"student_number":4322},
          "Lara":{"grade":74,"student_number":4042}}

In [10]:
# Method without numpy

student_name=list(students.keys())

grades=0
for st in range(len(student_name)):
    grades+=list(students.values())[st]['grade']
    
mean=grades/len(student_name)

In [43]:
# Method with numpy

import numpy as np
mean_grade=np.mean([i['grade'] for i in students.values()])

In [11]:
%%time
above=[['above'],[]]
equal=[['equal'],[]]
below=[['below'],[]]
gradesphrases=[above, equal, below]

for student in student_name:
    if students[student]['grade']>mean:
        above[1].append(student)
    elif students[student]['grade']==mean:
        equal[1].append(student)
    else:
        below[1].append(student)

# phrases with 'is' & 'are'

for level in gradesphrases:
    phrase="Grade(s) of "
    if len(level[1])>1:
        for student in level[1]:
            phrase+=student + ' '
        print(phrase + "are " + level[0][0] + " the average.")
    if len(level[1])==1:
        for student in level[1]:
            print(phrase + student + "is " + level[0][0] + "the average.")

Grade(s) of Jane Pat are above the average.
Grade(s) of Denis Max Lara are below the average.
CPU times: user 195 µs, sys: 86 µs, total: 281 µs
Wall time: 217 µs


In [45]:
# Other solution 1

L1=[]

for key, value in students.items():
    L1.append(value)

L1

allgrades=[i['grade'] for i in L1 if 'grade' in i]
allgrades

[90, 81, 70, 72, 74]

In [46]:
mean=0
for i in allgrades:
    mean+=i
mean=mean/len(allgrades)
print("Mean grade is " + str(mean))

Mean grade is 77.4


In [47]:
zipped=dict(zip(students.keys(), allgrades))

for key in zipped:
    if zipped[key]>mean:
        print("Grade of " + str(key) + " is above the average.")
    elif zipped[key]==mean:
        print("Grade of " + str(key) + " is equal the average.")
    else:
        print("Grade of " + str(key) + " is below the average.")

Grade of Jane is above the average.
Grade of Pat is above the average.
Grade of Denis is below the average.
Grade of Max is below the average.
Grade of Lara is below the average.


## Question 5

In [8]:
remain=200
transaction=0
while remain>0:
    print(str(remain) + " tickets remaining")
    x=input('How many do you want to buy? /n Minimum 1, Maximum 4')
    print(x)
    transaction+=1
    remain=remain-int(x)
print(str(transaction) + "sales transactions")

200 tickets remaining
How many do you want to buy? /n Minimum 1, Maximum 410
10
190 tickets remaining
How many do you want to buy? /n Minimum 1, Maximum 420
20
170 tickets remaining
How many do you want to buy? /n Minimum 1, Maximum 440
40
130 tickets remaining
How many do you want to buy? /n Minimum 1, Maximum 430
30
100 tickets remaining
How many do you want to buy? /n Minimum 1, Maximum 420
20
80 tickets remaining
How many do you want to buy? /n Minimum 1, Maximum 410
10
70 tickets remaining
How many do you want to buy? /n Minimum 1, Maximum 440
40
30 tickets remaining
How many do you want to buy? /n Minimum 1, Maximum 430
30
8sales transactions
CPU times: user 26.4 ms, sys: 9.81 ms, total: 36.3 ms
Wall time: 10.3 s
